# gruvbox — generated, do not hand-edit
foreground              #ebdbb2
background              #282828
selection_foreground    #282828
selection_background    #fe8019
cursor                  #fe8019
cursor_text_color       #282828
url_color               #fe8019

active_border_color     #d79921
inactive_border_color   #504945
bell_border_color       #d79921

active_tab_foreground   #282828
active_tab_background   #d79921
inactive_tab_foreground #ebdbb2
inactive_tab_background #1d2021
tab_bar_background      #1d2021

color0  #3c3836
color8  #504945
color1  #cc241d
color9  #cc241d
color2  #98971a
color10 #98971a
color3  #d79921
color11 #d79921
color4  #fe8019
color12 #fe8019
color5  #d79921
color13 #d79921
color6  #fe8019
color14 #fe8019
color7  #ebdbb2
color15 #d5c4a1
