# dracula — generated, do not hand-edit
foreground              #f8f8f2
background              #282a36
selection_foreground    #282a36
selection_background    #bd93f9
cursor                  #bd93f9
cursor_text_color       #282a36
url_color               #bd93f9

active_border_color     #bd93f9
inactive_border_color   #565971
bell_border_color       #f1fa8c

active_tab_foreground   #282a36
active_tab_background   #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #21222c
tab_bar_background      #21222c

color0  #44475a
color8  #565971
color1  #ff5555
color9  #ff5555
color2  #50fa7b
color10 #50fa7b
color3  #f1fa8c
color11 #f1fa8c
color4  #ff79c6
color12 #ff79c6
color5  #bd93f9
color13 #bd93f9
color6  #ff79c6
color14 #ff79c6
color7  #f8f8f2
color15 #bfbfd4
