# nord — generated, do not hand-edit
foreground              #e5e9f0
background              #2e3440
selection_foreground    #2e3440
selection_background    #88c0d0
cursor                  #88c0d0
cursor_text_color       #2e3440
url_color               #88c0d0

active_border_color     #88c0d0
inactive_border_color   #434c5e
bell_border_color       #ebcb8b

active_tab_foreground   #2e3440
active_tab_background   #88c0d0
inactive_tab_foreground #e5e9f0
inactive_tab_background #242933
tab_bar_background      #242933

color0  #3b4252
color8  #434c5e
color1  #bf616a
color9  #bf616a
color2  #a3be8c
color10 #a3be8c
color3  #ebcb8b
color11 #ebcb8b
color4  #5e81ac
color12 #5e81ac
color5  #88c0d0
color13 #88c0d0
color6  #5e81ac
color14 #5e81ac
color7  #e5e9f0
color15 #d8dee9
